Css three column layout
SeungjooKimSJ/c0121-code-solutions pull request #18
Opened 2021-01-22 08:20 UTC by SeungjooKimSJ

![image](https://user-images.githubusercontent.com/68725614/105465350-a83dfc00-5c47-11eb-998b-0569fce4206f.png)

2021-01-23 01:13 UTC, codingcodymiller requested changes
Hey Seungjoo! The edges of your images are cut off and don't match the example, please revise

2021-01-26 23:26 UTC, codingcodymiller requested changes
Nice work so far! A couple minor changes:

2021-01-26 23:26 UTC, codingcodymiller commented on css-three-column-layout/styles.css
> +.third {
Rather than three separate classes, combine this into one class named something like `.column-third`

2021-01-26 23:26 UTC, codingcodymiller commented on css-three-column-layout/styles.css
> +  position: absolute;
This does not need to be `absolute`

2021-01-26 23:26 UTC, codingcodymiller commented on css-three-column-layout/styles.css
> +  top: 90%;
If you undo the `absolute` positioning above, this should no longer be necessary.

2021-01-28 16:48 UTC, thebearingedge requested changes

2021-01-28 16:48 UTC, thebearingedge commented on css-three-column-layout/styles.css
> +  /* top: 90%; */
Please let us know when this is removed. In general, you should never turn in commented out code.

2021-01-28 16:48 UTC, thebearingedge commented on css-three-column-layout/styles.css
> +}
This was already done in `reset.css`, so you can remove it.

2021-01-28 20:12 UTC, thebearingedge approved these changes

2021-02-01 08:31 UTC, merged