Completed css-four-column-layout. | Seungjoo Kim
SeungjooKimSJ/c0121-code-solutions pull request #26
Opened 2021-01-26 06:58 UTC by SeungjooKimSJ

![image](https://user-images.githubusercontent.com/68725614/105810999-c7e36600-5f60-11eb-845f-96254bc3beb1.png)

2021-01-28 17:03 UTC, thebearingedge requested changes

2021-01-28 17:03 UTC, thebearingedge commented on css-four-column-layout/styles.css
> +  /* border: 1px solid black; */
Please delete all commented code.

2021-01-28 20:09 UTC, codingcodymiller requested changes
Hey Seungjoo! A couple minor notes here:

2021-01-28 20:09 UTC, codingcodymiller commented on css-four-column-layout/styles.css
> +  position: relative;
This line is unnecessary

2021-01-28 20:09 UTC, codingcodymiller commented on css-four-column-layout/styles.css
> +  position: relative;
This line is unnecessary

2021-01-28 20:09 UTC, codingcodymiller commented on css-four-column-layout/styles.css
> +  position: relative;
This line is unnecessary

2021-02-01 17:00 UTC, thebearingedge approved these changes

2021-02-02 07:53 UTC, merged